# SwiftLint is used to detect issues that SwiftFormat can not fix automatically.
# Therefore rules like "trailing_semicolon" and "vertical_whitespace" are not enabled.
only_rules:
  - balanced_xctest_lifecycle
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - compiler_protocol_init
  - computed_accessors_order
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - custom_rules
  - discarded_notification_center_observer
  - empty_collection_literal
  - empty_count
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - first_where
  - for_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - legacy_random
  - mark
  - multiline_arguments
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - nslocalizedstring_key
  - nsobject_prefer_isequal
  - overridden_super_call
  - redundant_type_annotation
  - shorthand_operator
  - syntactic_sugar
  - unavailable_function
  - unused_enumerated
  - weak_delegate
excluded:
  .build
