name: SwiftFormat + SwiftLint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Mint
        run: brew install mint

      - name: SwiftFormat
        run: swiftformat --lint --verbose

      - name: SwiftLint
        run: swiftlint --strict --quiet